/* parser generated by jison 0.4.15-102 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(errorMessage, errorHash),
    JisonParserError: function(msg, hash),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$, ...),
                (where `...` denotes the (optional) additional arguments the user passed to `parser.parse(str, ...)`)
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        ERROR: 2,
        JisonLexerError: function(msg, hash),
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        reject: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),
        stateStackSize: function(),

        options: { ... },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (array describing the set of expected tokens; may be empty when we cannot easily produce such a set)
    recoverable: (boolean: TRUE when the parser MAY have an error recovery rule available for this particular error)
  }
  
  You can specify parser options by setting / modifying the `.yy` object of your Parser instance.
  These options are available:
  
  ### options which are global for all parser instances
  
  Parser.pre_parse: function(yy)
                              optional: you can specify a pre_parse() function in the chunk following the grammar, 
                              i.e. after the last `%%`.
  Parser.post_parse: function(yy, retval) { return retval; }
                              optional: you can specify a post_parse() function in the chunk following the grammar, 
                              i.e. after the last `%%`. When it does not return any value, the parser will return 
                              the original `retval`.
  
  ### options which can be set up per parser instance
  
  yy: {
      pre_parse:  function(yy)
                              optional: is invoked before the parse cycle starts (and before the first invocation 
                              of `lex()`) but immediately after the invocation of parser.pre_parse()).
      post_parse: function(yy, retval) { return retval; }
                              optional: is invoked when the parse terminates due to success ('accept') or failure 
                              (even when exceptions are thrown).  `retval` contains the return value to be produced
                              by `Parser.parse()`; this function can override the return value by returning another. 
                              When it does not return any value, the parser will return the original `retval`. 
                              This function is invoked immediately before `Parser.post_parse()`.
      parseError: function(str, hash)
                              optional: overrides the default `parseError` function.
  }
  
  parser.lexer.options: {
      ranges: boolean         optional: true ==> token location info will include a .range[] member.
      flex: boolean           optional: true ==> flex-like lexing behaviour where the rules are tested
                                                 exhaustively to find the longest match.
      backtrack_lexer: boolean
                              optional: true ==> lexer regexes are tested in order and for each matching
                                                 regex the action code is invoked; the lexer terminates
                                                 the scan when a token is returned by the action code.
      pre_lex:  function()
                              optional: is invoked before the lexer is invoked to produce another token.
                              `this` refers to the Lexer object.
      post_lex: function(token) { return token; }
                              optional: is invoked when the lexer has produced a token `token`;
                              this function can override the returned token value by returning another.
                              When it does not return any (truthy) value, the lexer will return the original `token`.
                              `this` refers to the Lexer object.
  }
*/
var parser = (function () {
// http://stackoverflow.com/questions/1382107/whats-a-good-way-to-extend-error-in-javascript
// http://stackoverflow.com/questions/1382107/whats-a-good-way-to-extend-error-in-javascript
function JisonParserError(msg, hash) {
    this.message = msg;
    this.hash = hash;
    var stacktrace = (new Error(msg)).stack;
    if (stacktrace) {
      this.stack = stacktrace;
    }
}
JisonParserError.prototype = Object.create(Error.prototype);
JisonParserError.prototype.constructor = JisonParserError;
JisonParserError.prototype.name = 'JisonParserError';

function __expand__(k, v, o) {
  o = o || {};
  for (var l = k.length; l--; ) {
    o[k[l]] = v;
  }
  return o;
}

var $V0=[5,11,14,16,18,23,24,31,33,36,37,38],
    $V1=[11,63],
    $V2=[5,11,14,16,18,23,24,31,33,36,37,38,43,63],
    $V3=[5,11,14,16,18,23,24,31,33,36,37,38,45,63],
    $V4=[5,11,14,16,18,23,24,31,33,36,37,38,45,52,53,63,70,73],
    $V5=[5,8,11,14,16,18,23,24,31,33,36,37,38,52,53,63,77],
    $V6=[8,77],
    $V7=[5,8],
    $V8=[5,11,14,16,18,23,24,31,33,36,37,38,43,45,63],
    $V9=[11,45,52,53,63,64,69,70,73],
    $Va=[11,52,53,70,73],
    $Vb=[11,45,52,53,63,64,65,69,70,73],
    $Vc=[11,45,52,53,62,63,64,65,69,70,73],
    $Vd=[11,45,52,53,62,63,64,65,66,67,68,69,70,73],
    $Ve=[45,53,63,64],
    $Vf=[70,72];

var parser = {
trace: function trace() { },
JisonParserError: JisonParserError,
yy: {},
symbols_: {
  "error": 2,
  "spec": 3,
  "declaration_list": 4,
  "%%": 5,
  "grammar": 6,
  "optional_end_block": 7,
  "EOF": 8,
  "extra_parser_module_code": 9,
  "optional_action_header_block": 10,
  "ACTION": 11,
  "include_macro_code": 12,
  "declaration": 13,
  "START": 14,
  "id": 15,
  "LEX_BLOCK": 16,
  "operator": 17,
  "TOKEN": 18,
  "full_token_definitions": 19,
  "parse_param": 20,
  "parser_type": 21,
  "options": 22,
  "UNKNOWN_DECL": 23,
  "OPTIONS": 24,
  "option_list": 25,
  "OPTIONS_END": 26,
  "option": 27,
  "NAME": 28,
  "=": 29,
  "OPTION_VALUE": 30,
  "PARSE_PARAM": 31,
  "token_list": 32,
  "PARSER_TYPE": 33,
  "symbol": 34,
  "associativity": 35,
  "LEFT": 36,
  "RIGHT": 37,
  "NONASSOC": 38,
  "full_token_definition": 39,
  "optional_token_type": 40,
  "optional_token_value": 41,
  "optional_token_description": 42,
  "TOKEN_TYPE": 43,
  "INTEGER": 44,
  "STRING": 45,
  "id_list": 46,
  "token_id": 47,
  "production_list": 48,
  "production": 49,
  ":": 50,
  "handle_list": 51,
  ";": 52,
  "|": 53,
  "handle_action": 54,
  "handle": 55,
  "prec": 56,
  "action": 57,
  "expression_suffix": 58,
  "handle_sublist": 59,
  "expression": 60,
  "suffix": 61,
  "ALIAS": 62,
  "ID": 63,
  "(": 64,
  ")": 65,
  "*": 66,
  "?": 67,
  "+": 68,
  "PREC": 69,
  "{": 70,
  "action_body": 71,
  "}": 72,
  "ARROW_ACTION": 73,
  "action_comments_body": 74,
  "ACTION_BODY": 75,
  "optional_module_code_chunk": 76,
  "INCLUDE": 77,
  "PATH": 78,
  "module_code_chunk": 79,
  "CODE": 80,
  "$accept": 0,
  "$end": 1
},
terminals_: {
  2: "error",
  5: "%%",
  8: "EOF",
  11: "ACTION",
  14: "START",
  16: "LEX_BLOCK",
  18: "TOKEN",
  23: "UNKNOWN_DECL",
  24: "OPTIONS",
  26: "OPTIONS_END",
  28: "NAME",
  29: "=",
  30: "OPTION_VALUE",
  31: "PARSE_PARAM",
  33: "PARSER_TYPE",
  36: "LEFT",
  37: "RIGHT",
  38: "NONASSOC",
  43: "TOKEN_TYPE",
  44: "INTEGER",
  45: "STRING",
  50: ":",
  52: ";",
  53: "|",
  62: "ALIAS",
  63: "ID",
  64: "(",
  65: ")",
  66: "*",
  67: "?",
  68: "+",
  69: "PREC",
  70: "{",
  72: "}",
  73: "ARROW_ACTION",
  75: "ACTION_BODY",
  77: "INCLUDE",
  78: "PATH",
  80: "CODE"
},
productions_: [
  0,
  [
    3,
    5
  ],
  [
    7,
    0
  ],
  [
    7,
    2
  ],
  [
    10,
    0
  ],
  [
    10,
    2
  ],
  [
    10,
    2
  ],
  [
    4,
    2
  ],
  [
    4,
    0
  ],
  [
    13,
    2
  ],
  [
    13,
    1
  ],
  [
    13,
    1
  ],
  [
    13,
    2
  ],
  [
    13,
    1
  ],
  [
    13,
    1
  ],
  [
    13,
    1
  ],
  [
    13,
    1
  ],
  [
    13,
    1
  ],
  [
    13,
    1
  ],
  [
    22,
    3
  ],
  [
    25,
    2
  ],
  [
    25,
    1
  ],
  [
    27,
    1
  ],
  [
    27,
    3
  ],
  [
    27,
    3
  ],
  [
    20,
    2
  ],
  [
    21,
    2
  ],
  [
    17,
    2
  ],
  [
    35,
    1
  ],
  [
    35,
    1
  ],
  [
    35,
    1
  ],
  [
    32,
    2
  ],
  [
    32,
    1
  ],
  [
    19,
    2
  ],
  [
    19,
    1
  ],
  [
    39,
    4
  ],
  [
    40,
    0
  ],
  [
    40,
    1
  ],
  [
    41,
    0
  ],
  [
    41,
    1
  ],
  [
    42,
    0
  ],
  [
    42,
    1
  ],
  [
    46,
    2
  ],
  [
    46,
    1
  ],
  [
    47,
    2
  ],
  [
    47,
    1
  ],
  [
    6,
    2
  ],
  [
    48,
    2
  ],
  [
    48,
    1
  ],
  [
    49,
    4
  ],
  [
    51,
    3
  ],
  [
    51,
    1
  ],
  [
    54,
    3
  ],
  [
    55,
    2
  ],
  [
    55,
    0
  ],
  [
    59,
    3
  ],
  [
    59,
    1
  ],
  [
    58,
    3
  ],
  [
    58,
    2
  ],
  [
    60,
    1
  ],
  [
    60,
    1
  ],
  [
    60,
    3
  ],
  [
    61,
    0
  ],
  [
    61,
    1
  ],
  [
    61,
    1
  ],
  [
    61,
    1
  ],
  [
    56,
    2
  ],
  [
    56,
    0
  ],
  [
    34,
    1
  ],
  [
    34,
    1
  ],
  [
    15,
    1
  ],
  [
    57,
    3
  ],
  [
    57,
    1
  ],
  [
    57,
    1
  ],
  [
    57,
    1
  ],
  [
    57,
    0
  ],
  [
    71,
    0
  ],
  [
    71,
    1
  ],
  [
    71,
    5
  ],
  [
    71,
    4
  ],
  [
    74,
    1
  ],
  [
    74,
    2
  ],
  [
    9,
    1
  ],
  [
    9,
    3
  ],
  [
    12,
    2
  ],
  [
    12,
    2
  ],
  [
    79,
    1
  ],
  [
    79,
    2
  ],
  [
    76,
    1
  ],
  [
    76,
    0
  ]
],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1 : 
/*! Production::     spec : declaration_list %% grammar optional_end_block EOF */
 
            this.$ = $$[$0-4];
            if ($$[$0-1] && $$[$0-1].trim() !== '') {
                yy.addDeclaration(this.$, { include: $$[$0-1] });
            }
            return extend(this.$, $$[$0-2]);
         
break;
case 3 : 
/*! Production::     optional_end_block : %% extra_parser_module_code */
 case 25 : 
/*! Production::     parse_param : PARSE_PARAM token_list */
 case 26 : 
/*! Production::     parser_type : PARSER_TYPE symbol */
 case 44 : 
/*! Production::     token_id : TOKEN_TYPE id */
 case 45 : 
/*! Production::     token_id : id */
 case 59 : 
/*! Production::     expression : ID */
 case 68 : 
/*! Production::     symbol : id */
 case 69 : 
/*! Production::     symbol : STRING */
 case 70 : 
/*! Production::     id : ID */
 case 72 : 
/*! Production::     action : ACTION */
 case 73 : 
/*! Production::     action : include_macro_code */
 case 77 : 
/*! Production::     action_body : action_comments_body */
 case 80 : 
/*! Production::     action_comments_body : ACTION_BODY */
 case 82 : 
/*! Production::     extra_parser_module_code : optional_module_code_chunk */
 case 86 : 
/*! Production::     module_code_chunk : CODE */
 case 88 : 
/*! Production::     optional_module_code_chunk : module_code_chunk */
  this.$ = $$[$0];  
break;
case 4 : 
/*! Production::     optional_action_header_block :  */
 case 8 : 
/*! Production::     declaration_list :  */
  this.$ = {};  
break;
case 5 : 
/*! Production::     optional_action_header_block : optional_action_header_block ACTION */
 case 6 : 
/*! Production::     optional_action_header_block : optional_action_header_block include_macro_code */
 
            this.$ = $$[$0-1];
            yy.addDeclaration(this.$, { actionInclude: $$[$0] });
         
break;
case 7 : 
/*! Production::     declaration_list : declaration_list declaration */
  this.$ = $$[$0-1]; yy.addDeclaration(this.$, $$[$0]);  
break;
case 9 : 
/*! Production::     declaration : START id */
  this.$ = {start: $$[$0]};  
break;
case 10 : 
/*! Production::     declaration : LEX_BLOCK */
  this.$ = {lex: $$[$0]};  
break;
case 11 : 
/*! Production::     declaration : operator */
  this.$ = {operator: $$[$0]};  
break;
case 12 : 
/*! Production::     declaration : TOKEN full_token_definitions */
  this.$ = {token_list: $$[$0]};  
break;
case 13 : 
/*! Production::     declaration : ACTION */
 case 14 : 
/*! Production::     declaration : include_macro_code */
  this.$ = {include: $$[$0]};  
break;
case 15 : 
/*! Production::     declaration : parse_param */
  this.$ = {parseParam: $$[$0]};  
break;
case 16 : 
/*! Production::     declaration : parser_type */
  this.$ = {parserType: $$[$0]};  
break;
case 17 : 
/*! Production::     declaration : options */
  this.$ = {options: $$[$0]};  
break;
case 18 : 
/*! Production::     declaration : UNKNOWN_DECL */
  this.$ = {unknownDecl: $$[$0]};  
break;
case 19 : 
/*! Production::     options : OPTIONS option_list OPTIONS_END */
 case 71 : 
/*! Production::     action : { action_body } */
  this.$ = $$[$0-1];  
break;
case 20 : 
/*! Production::     option_list : option_list option */
 case 31 : 
/*! Production::     token_list : token_list symbol */
 case 33 : 
/*! Production::     full_token_definitions : full_token_definitions full_token_definition */
 case 42 : 
/*! Production::     id_list : id_list id */
  this.$ = $$[$0-1]; this.$.push($$[$0]);  
break;
case 21 : 
/*! Production::     option_list : option */
 case 32 : 
/*! Production::     token_list : symbol */
 case 34 : 
/*! Production::     full_token_definitions : full_token_definition */
 case 43 : 
/*! Production::     id_list : id */
 case 51 : 
/*! Production::     handle_list : handle_action */
  this.$ = [$$[$0]];  
break;
case 22 : 
/*! Production::     option : NAME */
  this.$ = [$$[$0], true];  
break;
case 23 : 
/*! Production::     option : NAME = OPTION_VALUE */
 case 24 : 
/*! Production::     option : NAME = NAME */
  this.$ = [$$[$0-2], $$[$0]];  
break;
case 27 : 
/*! Production::     operator : associativity token_list */
  this.$ = [$$[$0-1]]; this.$.push.apply(this.$, $$[$0]);  
break;
case 28 : 
/*! Production::     associativity : LEFT */
  this.$ = 'left';  
break;
case 29 : 
/*! Production::     associativity : RIGHT */
  this.$ = 'right';  
break;
case 30 : 
/*! Production::     associativity : NONASSOC */
  this.$ = 'nonassoc';  
break;
case 35 : 
/*! Production::     full_token_definition : optional_token_type id optional_token_value optional_token_description */
 
            this.$ = {id: $$[$0-2]};
            if ($$[$0-3]) {
                this.$.type = $$[$0-3];
            }
            if ($$[$0-1]) {
                this.$.value = $$[$0-1];
            }
            if ($$[$0]) {
                this.$.description = $$[$0];
            }
         
break;
case 36 : 
/*! Production::     optional_token_type :  */
 case 38 : 
/*! Production::     optional_token_value :  */
 case 40 : 
/*! Production::     optional_token_description :  */
  this.$ = false;  
break;
case 46 : 
/*! Production::     grammar : optional_action_header_block production_list */
 
            this.$ = $$[$0-1];
            this.$.grammar = $$[$0];
         
break;
case 47 : 
/*! Production::     production_list : production_list production */
 
            this.$ = $$[$0-1];
            if ($$[$0][0] in this.$) {
                this.$[$$[$0][0]] = this.$[$$[$0][0]].concat($$[$0][1]);
            } else {
                this.$[$$[$0][0]] = $$[$0][1];
            }
         
break;
case 48 : 
/*! Production::     production_list : production */
  this.$ = {}; this.$[$$[$0][0]] = $$[$0][1];  
break;
case 49 : 
/*! Production::     production : id : handle_list ; */
 this.$ = [$$[$0-3], $$[$0-1]]; 
break;
case 50 : 
/*! Production::     handle_list : handle_list | handle_action */
 
            this.$ = $$[$0-2];
            this.$.push($$[$0]);
         
break;
case 52 : 
/*! Production::     handle_action : handle prec action */
 
            this.$ = [($$[$0-2].length ? $$[$0-2].join(' ') : '')];
            if ($$[$0]) {
                this.$.push($$[$0]);
            }
            if ($$[$0-1]) {
                this.$.push($$[$0-1]);
            }
            if (this.$.length === 1) {
                this.$ = this.$[0];
            }
         
break;
case 53 : 
/*! Production::     handle : handle expression_suffix */
 
            this.$ = $$[$0-1];
            this.$.push($$[$0]);
         
break;
case 54 : 
/*! Production::     handle :  */
 
            this.$ = [];
         
break;
case 55 : 
/*! Production::     handle_sublist : handle_sublist | handle */
 
            this.$ = $$[$0-2];
            this.$.push($$[$0].join(' '));
         
break;
case 56 : 
/*! Production::     handle_sublist : handle */
 
            this.$ = [$$[$0].join(' ')];
         
break;
case 57 : 
/*! Production::     expression_suffix : expression suffix ALIAS */
 
            this.$ = $$[$0-2] + $$[$0-1] + "[" + $$[$0] + "]";
         
break;
case 58 : 
/*! Production::     expression_suffix : expression suffix */
 case 81 : 
/*! Production::     action_comments_body : action_comments_body ACTION_BODY */
 case 87 : 
/*! Production::     module_code_chunk : module_code_chunk CODE */
 
            this.$ = $$[$0-1] + $$[$0];
         
break;
case 60 : 
/*! Production::     expression : STRING */
 
            // Re-encode the string *anyway* as it will
            // be made part of the rule rhs a.k.a. production (type: *string*) again and we want
            // to be able to handle all tokens, including *significant space*
            // encoded as literal tokens in a grammar such as this: `rule: A ' ' B`.
            if ($$[$0].indexOf("'") >= 0) {
                this.$ = '"' + $$[$0] + '"';
            } else {
                this.$ = "'" + $$[$0] + "'";
            }
         
break;
case 61 : 
/*! Production::     expression : ( handle_sublist ) */
 
            this.$ = '(' + $$[$0-1].join(' | ') + ')';
         
break;
case 62 : 
/*! Production::     suffix :  */
 case 75 : 
/*! Production::     action :  */
 case 76 : 
/*! Production::     action_body :  */
 case 89 : 
/*! Production::     optional_module_code_chunk :  */
  this.$ = '';  
break;
case 66 : 
/*! Production::     prec : PREC symbol */
 
            this.$ = { prec: $$[$0] };
         
break;
case 67 : 
/*! Production::     prec :  */
 
            this.$ = null;
         
break;
case 74 : 
/*! Production::     action : ARROW_ACTION */
  this.$ = '$$ =' + $$[$0] + ';';  
break;
case 78 : 
/*! Production::     action_body : action_body { action_body } action_comments_body */
  this.$ = $$[$0-4] + $$[$0-3] + $$[$0-2] + $$[$0-1] + $$[$0];  
break;
case 79 : 
/*! Production::     action_body : action_body { action_body } */
  this.$ = $$[$0-3] + $$[$0-2] + $$[$0-1] + $$[$0];  
break;
case 83 : 
/*! Production::     extra_parser_module_code : optional_module_code_chunk include_macro_code extra_parser_module_code */
  this.$ = $$[$0-2] + $$[$0-1] + $$[$0];  
break;
case 84 : 
/*! Production::     include_macro_code : INCLUDE PATH */
  
            var fs = require('fs');
            var fileContent = fs.readFileSync($$[$0], { encoding: 'utf-8' });
            // And no, we don't support nested '%include':
            this.$ = '\n// Included by Jison: ' + $$[$0] + ':\n\n' + fileContent + '\n\n// End Of Include by Jison: ' + $$[$0] + '\n\n';
         
break;
case 85 : 
/*! Production::     include_macro_code : INCLUDE error */
  
            console.error("%include MUST be followed by a valid file path"); 
         
break;
}
},
table: [
  __expand__($V0, [
      2,
      8
    ], {3:1,4:2,77:[
      2,
      8
    ]
  }),
  {
    1: [
      3
    ]
  },
  {
    5: [
      1,
      3
    ],
    11: [
      1,
      9
    ],
    12: 10,
    13: 4,
    14: [
      1,
      5
    ],
    16: [
      1,
      6
    ],
    17: 7,
    18: [
      1,
      8
    ],
    20: 11,
    21: 12,
    22: 13,
    23: [
      1,
      14
    ],
    24: [
      1,
      19
    ],
    31: [
      1,
      17
    ],
    33: [
      1,
      18
    ],
    35: 15,
    36: [
      1,
      20
    ],
    37: [
      1,
      21
    ],
    38: [
      1,
      22
    ],
    77: [
      1,
      16
    ]
  },
  __expand__($V1, [
      2,
      4
    ], {6:23,10:24,77:[
      2,
      4
    ]
  }),
  __expand__($V0, [
      2,
      7
    ], {77:[
      2,
      7
    ]
  }),
  {
    15: 25,
    63: [
      1,
      26
    ]
  },
  __expand__($V0, [
      2,
      10
    ], {77:[
      2,
      10
    ]
  }),
  __expand__($V0, [
      2,
      11
    ], {77:[
      2,
      11
    ]
  }),
  {
    19: 27,
    39: 28,
    40: 29,
    43: [
      1,
      30
    ],
    63: [
      2,
      36
    ]
  },
  __expand__($V0, [
      2,
      13
    ], {77:[
      2,
      13
    ]
  }),
  __expand__($V0, [
      2,
      14
    ], {77:[
      2,
      14
    ]
  }),
  __expand__($V0, [
      2,
      15
    ], {77:[
      2,
      15
    ]
  }),
  __expand__($V0, [
      2,
      16
    ], {77:[
      2,
      16
    ]
  }),
  __expand__($V0, [
      2,
      17
    ], {77:[
      2,
      17
    ]
  }),
  __expand__($V0, [
      2,
      18
    ], {77:[
      2,
      18
    ]
  }),
  {
    15: 33,
    32: 31,
    34: 32,
    45: [
      1,
      34
    ],
    63: [
      1,
      26
    ]
  },
  {
    2: [
      1,
      36
    ],
    78: [
      1,
      35
    ]
  },
  {
    15: 33,
    32: 37,
    34: 32,
    45: [
      1,
      34
    ],
    63: [
      1,
      26
    ]
  },
  {
    15: 33,
    34: 38,
    45: [
      1,
      34
    ],
    63: [
      1,
      26
    ]
  },
  {
    25: 39,
    27: 40,
    28: [
      1,
      41
    ]
  },
  {
    45: [
      2,
      28
    ],
    63: [
      2,
      28
    ]
  },
  {
    45: [
      2,
      29
    ],
    63: [
      2,
      29
    ]
  },
  {
    45: [
      2,
      30
    ],
    63: [
      2,
      30
    ]
  },
  {
    5: [
      1,
      43
    ],
    7: 42,
    8: [
      2,
      2
    ]
  },
  {
    11: [
      1,
      45
    ],
    12: 46,
    15: 48,
    48: 44,
    49: 47,
    63: [
      1,
      26
    ],
    77: [
      1,
      16
    ]
  },
  __expand__($V0, [
      2,
      9
    ], {77:[
      2,
      9
    ]
  }),
  __expand__([5,11,14,16,18,23,24,31,33,36,37,38,43,44,45,50,52,53,63,70,73], [
      2,
      70
    ], {77:[
      2,
      70
    ]
  }),
  __expand__($V0, [
      2,
      12
    ], {40:29,39:49,43:[
      1,
      30
    ],63:[
      2,
      36
    ],77:[
      2,
      12
    ]
  }),
  __expand__($V2, [
      2,
      34
    ], {77:[
      2,
      34
    ]
  }),
  {
    15: 50,
    63: [
      1,
      26
    ]
  },
  {
    63: [
      2,
      37
    ]
  },
  __expand__($V0, [
      2,
      27
    ], {15:33,34:51,45:[
      1,
      34
    ],63:[
      1,
      26
    ],77:[
      2,
      27
    ]
  }),
  __expand__($V3, [
      2,
      32
    ], {77:[
      2,
      32
    ]
  }),
  __expand__($V4, [
      2,
      68
    ], {77:[
      2,
      68
    ]
  }),
  __expand__($V4, [
      2,
      69
    ], {77:[
      2,
      69
    ]
  }),
  __expand__($V5, [
      2,
      84
    ], {80:[
      2,
      84
    ]
  }),
  __expand__($V5, [
      2,
      85
    ], {80:[
      2,
      85
    ]
  }),
  __expand__($V0, [
      2,
      25
    ], {15:33,34:51,45:[
      1,
      34
    ],63:[
      1,
      26
    ],77:[
      2,
      25
    ]
  }),
  __expand__($V0, [
      2,
      26
    ], {77:[
      2,
      26
    ]
  }),
  {
    26: [
      1,
      52
    ],
    27: 53,
    28: [
      1,
      41
    ]
  },
  {
    26: [
      2,
      21
    ],
    28: [
      2,
      21
    ]
  },
  __expand__([26,28], [
      2,
      22
    ], {29:[
      1,
      54
    ]
  }),
  {
    8: [
      1,
      55
    ]
  },
  __expand__($V6, [
      2,
      89
    ], {9:56,76:57,79:58,80:[
      1,
      59
    ]
  }),
  __expand__($V7, [
      2,
      46
    ], {15:48,49:60,63:[
      1,
      26
    ]
  }),
  __expand__($V1, [
      2,
      5
    ], {77:[
      2,
      5
    ]
  }),
  __expand__($V1, [
      2,
      6
    ], {77:[
      2,
      6
    ]
  }),
  __expand__($V7, [
      2,
      48
    ], {63:[
      2,
      48
    ]
  }),
  {
    50: [
      1,
      61
    ]
  },
  __expand__($V2, [
      2,
      33
    ], {77:[
      2,
      33
    ]
  }),
  __expand__($V8, [
      2,
      38
    ], {41:62,44:[
      1,
      63
    ],77:[
      2,
      38
    ]
  }),
  __expand__($V3, [
      2,
      31
    ], {77:[
      2,
      31
    ]
  }),
  __expand__($V0, [
      2,
      19
    ], {77:[
      2,
      19
    ]
  }),
  {
    26: [
      2,
      20
    ],
    28: [
      2,
      20
    ]
  },
  {
    28: [
      1,
      65
    ],
    30: [
      1,
      64
    ]
  },
  {
    1: [
      2,
      1
    ]
  },
  {
    8: [
      2,
      3
    ]
  },
  {
    8: [
      2,
      82
    ],
    12: 66,
    77: [
      1,
      16
    ]
  },
  __expand__($V6, [
      2,
      88
    ], {80:[
      1,
      67
    ]
  }),
  __expand__($V6, [
      2,
      86
    ], {80:[
      2,
      86
    ]
  }),
  __expand__($V7, [
      2,
      47
    ], {63:[
      2,
      47
    ]
  }),
  __expand__($V9, [
      2,
      54
    ], {51:68,54:69,55:70,77:[
      2,
      54
    ]
  }),
  __expand__($V2, [
      2,
      40
    ], {42:71,45:[
      1,
      72
    ],77:[
      2,
      40
    ]
  }),
  __expand__($V8, [
      2,
      39
    ], {77:[
      2,
      39
    ]
  }),
  {
    26: [
      2,
      23
    ],
    28: [
      2,
      23
    ]
  },
  {
    26: [
      2,
      24
    ],
    28: [
      2,
      24
    ]
  },
  __expand__($V6, [
      2,
      89
    ], {76:57,79:58,9:73,80:[
      1,
      59
    ]
  }),
  __expand__($V6, [
      2,
      87
    ], {80:[
      2,
      87
    ]
  }),
  {
    52: [
      1,
      74
    ],
    53: [
      1,
      75
    ]
  },
  {
    52: [
      2,
      51
    ],
    53: [
      2,
      51
    ]
  },
  __expand__($Va, [
      2,
      67
    ], {56:76,58:77,60:79,45:[
      1,
      81
    ],63:[
      1,
      80
    ],64:[
      1,
      82
    ],69:[
      1,
      78
    ],77:[
      2,
      67
    ]
  }),
  __expand__($V2, [
      2,
      35
    ], {77:[
      2,
      35
    ]
  }),
  __expand__($V2, [
      2,
      41
    ], {77:[
      2,
      41
    ]
  }),
  {
    8: [
      2,
      83
    ]
  },
  __expand__($V7, [
      2,
      49
    ], {63:[
      2,
      49
    ]
  }),
  __expand__($V9, [
      2,
      54
    ], {55:70,54:83,77:[
      2,
      54
    ]
  }),
  __expand__([52,53], [
      2,
      75
    ], {57:84,12:87,11:[
      1,
      86
    ],70:[
      1,
      85
    ],73:[
      1,
      88
    ],77:[
      1,
      16
    ]
  }),
  __expand__($Vb, [
      2,
      53
    ], {77:[
      2,
      53
    ]
  }),
  {
    15: 33,
    34: 89,
    45: [
      1,
      34
    ],
    63: [
      1,
      26
    ]
  },
  __expand__($Vc, [
      2,
      62
    ], {61:90,66:[
      1,
      91
    ],67:[
      1,
      92
    ],68:[
      1,
      93
    ],77:[
      2,
      62
    ]
  }),
  __expand__($Vd, [
      2,
      59
    ], {77:[
      2,
      59
    ]
  }),
  __expand__($Vd, [
      2,
      60
    ], {77:[
      2,
      60
    ]
  }),
  __expand__($Ve, [
      2,
      54
    ], {59:94,55:95,65:[
      2,
      54
    ]
  }),
  {
    52: [
      2,
      50
    ],
    53: [
      2,
      50
    ]
  },
  {
    52: [
      2,
      52
    ],
    53: [
      2,
      52
    ]
  },
  __expand__($Vf, [
      2,
      76
    ], {71:96,74:97,75:[
      1,
      98
    ]
  }),
  {
    52: [
      2,
      72
    ],
    53: [
      2,
      72
    ]
  },
  {
    52: [
      2,
      73
    ],
    53: [
      2,
      73
    ]
  },
  {
    52: [
      2,
      74
    ],
    53: [
      2,
      74
    ]
  },
  __expand__($Va, [
      2,
      66
    ], {77:[
      2,
      66
    ]
  }),
  __expand__($Vb, [
      2,
      58
    ], {62:[
      1,
      99
    ],77:[
      2,
      58
    ]
  }),
  __expand__($Vc, [
      2,
      63
    ], {77:[
      2,
      63
    ]
  }),
  __expand__($Vc, [
      2,
      64
    ], {77:[
      2,
      64
    ]
  }),
  __expand__($Vc, [
      2,
      65
    ], {77:[
      2,
      65
    ]
  }),
  {
    53: [
      1,
      101
    ],
    65: [
      1,
      100
    ]
  },
  {
    45: [
      1,
      81
    ],
    53: [
      2,
      56
    ],
    58: 77,
    60: 79,
    63: [
      1,
      80
    ],
    64: [
      1,
      82
    ],
    65: [
      2,
      56
    ]
  },
  {
    70: [
      1,
      103
    ],
    72: [
      1,
      102
    ]
  },
  __expand__($Vf, [
      2,
      77
    ], {75:[
      1,
      104
    ]
  }),
  __expand__($Vf, [
      2,
      80
    ], {75:[
      2,
      80
    ]
  }),
  __expand__($Vb, [
      2,
      57
    ], {77:[
      2,
      57
    ]
  }),
  __expand__($Vd, [
      2,
      61
    ], {77:[
      2,
      61
    ]
  }),
  __expand__($Ve, [
      2,
      54
    ], {55:105,65:[
      2,
      54
    ]
  }),
  {
    52: [
      2,
      71
    ],
    53: [
      2,
      71
    ]
  },
  __expand__($Vf, [
      2,
      76
    ], {74:97,71:106,75:[
      1,
      98
    ]
  }),
  __expand__($Vf, [
      2,
      81
    ], {75:[
      2,
      81
    ]
  }),
  {
    45: [
      1,
      81
    ],
    53: [
      2,
      55
    ],
    58: 77,
    60: 79,
    63: [
      1,
      80
    ],
    64: [
      1,
      82
    ],
    65: [
      2,
      55
    ]
  },
  {
    70: [
      1,
      103
    ],
    72: [
      1,
      107
    ]
  },
  __expand__($Vf, [
      2,
      79
    ], {74:108,75:[
      1,
      98
    ]
  }),
  __expand__($Vf, [
      2,
      78
    ], {75:[
      1,
      104
    ]
  })
],
defaultActions: {
  30: [
    2,
    37
  ],
  55: [
    2,
    1
  ],
  56: [
    2,
    3
  ],
  73: [
    2,
    83
  ]
},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        throw new this.JisonParserError(str, hash);
    }
},
parse: function parse(input) {
    var self = this,
        stack = [0],

        vstack = [null],    // semantic value stack
        lstack = [],        // location stack
        table = this.table,
        yytext = '',
        yylineno = 0,
        yyleng = 0,
        recovering = 0,     // (only used when the grammar contains error recovery rules)
        TERROR = 2,
        EOF = 1;

    var args = lstack.slice.call(arguments, 1);

    //this.reductionCount = this.shiftCount = 0;

    var lexer;
    if (this.__lexer__) {
        lexer = this.__lexer__;
    } else {
        lexer = this.__lexer__ = Object.create(this.lexer);
    }

    var sharedState = { 
      yy: {} 
    };
    // copy state
    for (var k in this.yy) {
      if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
        sharedState.yy[k] = this.yy[k];
      }
    }

    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc === 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);

    var ranges = lexer.options && lexer.options.ranges;

    // Does the shared state override the default `parseError` that already comes with this instance?
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } 

    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }

    function lex() {
        var token;
        token = lexer.lex() || EOF;
        // if token isn't its numeric value, convert
        if (typeof token !== 'number') {
            token = self.symbols_[token] || token;
        }
        return token;
    }

    var symbol;
    var preErrorSymbol = null;
    var state, action, a, r;
    var yyval = {};
    var p, len, len1, this_production, lstack_begin, lstack_end, newState;
    var expected = [];
    var retval = false;

    if (this.pre_parse) {
        this.pre_parse.call(this, sharedState.yy);
    }
    if (sharedState.yy.pre_parse) {
        sharedState.yy.pre_parse.call(this, sharedState.yy);
    }

    // Return the rule stack depth where the nearest error rule can be found.
    // Return FALSE when no error recovery rule was found.
    function locateNearestErrorRecoveryRule(state) {
        var stack_probe = stack.length - 1;
        var depth = 0;

        // try to recover from error
        for (;;) {
            // check for error recovery rule in this state
            if ((TERROR.toString()) in table[state]) {
                return depth;
            }
            if (state === 0 || stack_probe < 2) {
                return false; // No suitable error recovery rule available.
            }
            stack_probe -= 2; // popStack(1): [symbol, action]
            state = stack[stack_probe];
            ++depth;
        }
    }


    function collect_expected_token_set(state) {
        var tokenset = [];
        for (var p in table[state]) {
            if (p > TERROR) {
                if (self.terminal_descriptions_ && self.terminal_descriptions_[p]) {
                    tokenset.push(self.terminal_descriptions_[p]);
                }
                else if (self.terminals_[p]) {
                    tokenset.push("'" + self.terminals_[p] + "'");
                }
            }
        }
        return tokenset;
    }

    try {
        for (;;) {
            // retrieve state number from top of stack
            state = stack[stack.length - 1];

            // use default actions if available
            if (this.defaultActions[state]) {
                action = this.defaultActions[state];
            } else {
                if (symbol === null || typeof symbol === 'undefined') {
                    symbol = lex();
                }
                // read action for current state and first input
                action = table[state] && table[state][symbol];
            }

            // handle parse error
            if (typeof action === 'undefined' || !action.length || !action[0]) {
                var error_rule_depth;
                var errStr = '';

                if (!recovering) {
                    // first see if there's any chance at hitting an error recovery rule:
                    error_rule_depth = locateNearestErrorRecoveryRule(state);

                    // Report error
                    expected = collect_expected_token_set(state);
                    if (lexer.showPosition) {
                        errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ", got '" + (this.terminals_[symbol] || symbol) + "'";
                    } else {
                        errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' +
                                 (symbol === EOF ? 'end of input' :
                                  ("'" + (this.terminals_[symbol] || symbol) + "'"));
                    }
                    a = this.parseError(errStr, p = {
                        text: lexer.match,
                        token: this.terminals_[symbol] || symbol,
                        line: lexer.yylineno,
                        loc: yyloc,
                        expected: expected,
                        recoverable: (error_rule_depth !== false)
                    });
                    if (!p.recoverable) {
                        retval = a;
                        break;
                    }
                } else if (preErrorSymbol !== EOF) {
                    error_rule_depth = locateNearestErrorRecoveryRule(state);
                }

                // just recovered from another error
                if (recovering === 3) {
                    if (symbol === EOF || preErrorSymbol === EOF) {
                        retval = this.parseError(errStr || 'Parsing halted while starting to recover from another error.', {
                            text: lexer.match,
                            token: this.terminals_[symbol] || symbol,
                            line: lexer.yylineno,
                            loc: yyloc,
                            expected: expected,
                            recoverable: false
                        });
                        break;
                    }

                    // discard current lookahead and grab another
                    yyleng = lexer.yyleng;
                    yytext = lexer.yytext;
                    yylineno = lexer.yylineno;
                    yyloc = lexer.yylloc;
                    symbol = lex();
                }

                // try to recover from error
                if (error_rule_depth === false) {
                    retval = this.parseError(errStr || 'Parsing halted. No suitable error recovery rule available.', {
                        text: lexer.match,
                        token: this.terminals_[symbol] || symbol,
                        line: lexer.yylineno,
                        loc: yyloc,
                        expected: expected,
                        recoverable: false
                    });
                    break;
                }
                popStack(error_rule_depth);

                preErrorSymbol = (symbol === TERROR ? null : symbol); // save the lookahead token
                symbol = TERROR;         // insert generic error symbol as new lookahead
                state = stack[stack.length - 1];
                action = table[state] && table[state][TERROR];
                recovering = 3; // allow 3 real symbols to be shifted before reporting a new error
            }


            // this shouldn't happen, unless resolve defaults are off
            if (action[0] instanceof Array && action.length > 1) {
                retval = this.parseError('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected,
                    recoverable: false
                });
                break;
            }

            switch (action[0]) {
            case 1: // shift
                //this.shiftCount++;

                stack.push(symbol);
                vstack.push(lexer.yytext);
                lstack.push(lexer.yylloc);
                stack.push(action[1]); // push state
                symbol = null;
                if (!preErrorSymbol) { // normal execution / no error
                    yyleng = lexer.yyleng;
                    yytext = lexer.yytext;
                    yylineno = lexer.yylineno;
                    yyloc = lexer.yylloc;
                    if (recovering > 0) {
                        recovering--;
                    }
                } else {
                    // error just occurred, resume old lookahead f/ before error
                    symbol = preErrorSymbol;
                    preErrorSymbol = null;
                }
                continue;

            case 2:
                // reduce
                //this.reductionCount++;

                this_production = this.productions_[action[1]]; 
                len = this_production[1];
                lstack_end = lstack.length;
                lstack_begin = lstack_end - (len1 || 1);
                lstack_end--;

                // perform semantic action
                yyval.$ = vstack[vstack.length - len]; // default to $$ = $1
                // default location, uses first token for firsts, last for lasts
                yyval._$ = {
                    first_line: lstack[lstack_begin].first_line,
                    last_line: lstack[lstack_end].last_line,
                    first_column: lstack[lstack_begin].first_column,
                    last_column: lstack[lstack_end].last_column
                };
                if (ranges) {
                  yyval._$.range = [lstack[lstack_begin].range[0], lstack[lstack_end].range[1]];
                }
                r = this.performAction.apply(yyval, [yytext, yyleng, yylineno, sharedState.yy, action[1], vstack, lstack].concat(args));

                if (typeof r !== 'undefined') {
                    retval = r;
                    break;
                }

                // pop off stack
                if (len) {
                    popStack(len);
                }

                stack.push(this_production[0]);    // push nonterminal (reduce)
                vstack.push(yyval.$);
                lstack.push(yyval._$);
                // goto new state = table[STATE][NONTERMINAL]
                newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
                stack.push(newState);
                continue;

            case 3:
                // accept
                retval = true;
                break;
            }

            // break out of loop: we accept or fail with error
            break;
        }
    } finally {
        var rv;

        if (sharedState.yy.post_parse) {
            rv = sharedState.yy.post_parse.call(this, sharedState.yy, retval);
            if (typeof rv !== 'undefined') retval = rv;
        }
        if (this.post_parse) {
            rv = this.post_parse.call(this, sharedState.yy, retval);
            if (typeof rv !== 'undefined') retval = rv;
        }
    }

    return retval;
}
};

var transform = require('./ebnf-transform').transform;
var ebnf = false;


// transform ebnf to bnf if necessary
function extend(json, grammar) {
    json.bnf = ebnf ? transform(grammar.grammar) : grammar.grammar;
    if (grammar.actionInclude) {
        json.actionInclude = grammar.actionInclude;
    }
    return json;
}


/* generated by jison-lex 0.3.4-102 */
var lexer = (function () {
// http://stackoverflow.com/questions/1382107/whats-a-good-way-to-extend-error-in-javascript
// http://stackoverflow.com/questions/1382107/whats-a-good-way-to-extend-error-in-javascript
function JisonLexerError(msg, hash) {
    this.message = msg;
    this.hash = hash;
    var stacktrace = (new Error(msg)).stack;
    if (stacktrace) {
      this.stack = stacktrace;
    }
}
JisonLexerError.prototype = Object.create(Error.prototype);
JisonLexerError.prototype.constructor = JisonLexerError;
JisonLexerError.prototype.name = 'JisonLexerError';

var lexer = ({

EOF:1,

ERROR:2,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            return this.yy.parser.parseError(str, hash) || this.ERROR;
        } else {
            throw new this.JisonLexerError(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this._signaled_error_token = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0, 0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        // Count the linenumber up when we hit the LF (or a stand-alone CR).
        // On CRLF, the linenumber is incremented when you fetch the CR or the CRLF combo
        // and we advance immediately past the LF as well, returning both together as if 
        // it was all a single 'character' only.
        var slice_len = 1;
        var lines = false;
        if (ch === '\n') {
            lines = true;
        } else if (ch === '\r') {
            lines = true;
            var ch2 = this._input[1];
            if (ch2 === '\n') {
                slice_len++;
                ch += ch2;
                this.yytext += ch2;
                this.yyleng++;
                this.offset++;
                this.match += ch2;
                this.matched += ch2;
                if (this.options.ranges) {
                    this.yylloc.range[1]++;
                }
            }
        } 
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(slice_len);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - len);
        this.matched = this.matched.substr(0, this.matched.length - len);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                + oldLines[oldLines.length - lines.length].length - lines[0].length :
                this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            // when the parseError() call returns, we MUST ensure that the error is registered.
            // We accomplish this by signaling an 'error' token to be produced for the current
            // .lex() run.
            this._signaled_error_token = (this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: this.match,
                token: null,
                line: this.yylineno,
                loc: this.yylloc
            }) || this.ERROR);
        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// return (part of the) already matched input, i.e. for error messages
pastInput:function (maxSize) {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        if (maxSize < 0)
            maxSize = past.length;
        else if (!maxSize)
            maxSize = 20;
        return (past.length > maxSize ? '...' + past.substr(-maxSize) : past);
    },

// return (part of the) upcoming input, i.e. for error messages
upcomingInput:function (maxSize) {
        var next = this.match;
        if (maxSize < 0)
            maxSize = next.length + this._input.length;
        else if (!maxSize)
            maxSize = 20;
        if (next.length < maxSize) {
            next += this._input.substr(0, maxSize - next.length);
        }
        return (next.length > maxSize ? next.substr(0, maxSize) + '...' : next);
    },

// return a string which displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput().replace(/\s/g, ' ');
        var c = new Array(pre.length + 1).join('-');
        return pre + this.upcomingInput().replace(/\s/g, ' ') + '\n' + c + '^';
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function (match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset + this.yyleng];
        }
        this.offset += this.yyleng;
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        } else if (this._signaled_error_token) {
            // produce one 'error' token as .parseError() in reject() did not guarantee a failure signal by throwing an exception!
            token = this._signaled_error_token;
            this._signaled_error_token = false;
            return token;
        }
        return false;
    },

// return next match in input
next:function () {
        function clear() {
            this.yytext = '';
            this.yyleng = 0;
            this.match = '';
            this.matches = false;
            this._more = false;
            this._backtrack = false;
        }

        if (this.done) {
            clear.call(this);
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            clear.call(this);
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === '') {
            clear.call(this);
            this.done = true;
            return this.EOF;
        } else {
            token = this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: this.match + this._input,
                token: null,
                line: this.yylineno,
                loc: this.yylloc
            }) || this.ERROR;
            if (token === this.ERROR) {
                // we can try to recover from a lexer error that parseError() did not 'recover' for us, by moving forward one character at a time:
                if (!this.match.length) {
                    this.input();
                }
            }
            return token;
        }
    },

// return next match that has a token
lex:function lex() {
        var r;
        // allow the PRE/POST handlers set/modify the return token for maximum flexibility of the generated lexer:
        if (typeof this.options.pre_lex === 'function') {
            r = this.options.pre_lex.call(this);
        }
        while (!r) {
            r = this.next();
        }
        if (typeof this.options.post_lex === 'function') {
            // (also account for a userdef function which does not return any value: keep the token as is)
            r = this.options.post_lex.call(this, r) || r;
        }
        return r;
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin(condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules() {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions['INITIAL'].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return 'INITIAL';
        }
    },

// alias for begin(condition)
pushState:function pushState(condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {
  "easy_keyword_rules": true,
  "ranges": true
},
JisonLexerError: JisonLexerError,
performAction: function anonymous(yy, yy_, $avoiding_name_collisions, YY_START) {

var YYSTATE = YY_START;
switch($avoiding_name_collisions) {
case 0 : 
/*! Conditions:: token */ 
/*! Rule::       \r|\n */ 
 this.popState(); 
break;
case 1 : 
/*! Conditions:: token */ 
/*! Rule::       %% */ 
 this.popState(); 
break;
case 2 : 
/*! Conditions:: token */ 
/*! Rule::       ; */ 
 this.popState(); 
break;
case 3 : 
/*! Conditions:: bnf ebnf */ 
/*! Rule::       %% */ 
 this.pushState('code'); return 5; 
break;
case 11 : 
/*! Conditions:: options */ 
/*! Rule::       "(\\\\|\\"|[^"])*" */ 
 yy_.yytext = yy_.yytext.substr(1, yy_.yytext.length - 2); return 30; 
break;
case 12 : 
/*! Conditions:: options */ 
/*! Rule::       '(\\\\|\\'|[^'])*' */ 
 yy_.yytext = yy_.yytext.substr(1, yy_.yytext.length - 2); return 30; 
break;
case 14 : 
/*! Conditions:: options */ 
/*! Rule::       {BR}+ */ 
 this.popState(); return 26; 
break;
case 15 : 
/*! Conditions:: options */ 
/*! Rule::       \s+{BR}+ */ 
 this.popState(); return 26; 
break;
case 16 : 
/*! Conditions:: options */ 
/*! Rule::       \s+ */ 
 /* empty */ 
break;
case 17 : 
/*! Conditions:: bnf ebnf token INITIAL */ 
/*! Rule::       \s+ */ 
 /* skip whitespace */ 
break;
case 18 : 
/*! Conditions:: bnf ebnf token INITIAL */ 
/*! Rule::       \/\/.* */ 
 /* skip comment */ 
break;
case 19 : 
/*! Conditions:: bnf ebnf token INITIAL */ 
/*! Rule::       \/\*(.|\n|\r)*?\*\/ */ 
 /* skip comment */ 
break;
case 20 : 
/*! Conditions:: bnf ebnf token INITIAL */ 
/*! Rule::       \[{ID}\] */ 
 yy_.yytext = yy_.yytext.substr(1, yy_.yyleng - 2); return 62; 
break;
case 22 : 
/*! Conditions:: bnf ebnf token INITIAL */ 
/*! Rule::       "[^"]+" */ 
 yy_.yytext = yy_.yytext.substr(1, yy_.yyleng - 2); return 45; 
break;
case 23 : 
/*! Conditions:: bnf ebnf token INITIAL */ 
/*! Rule::       '[^']+' */ 
 yy_.yytext = yy_.yytext.substr(1, yy_.yyleng - 2); return 45; 
break;
case 28 : 
/*! Conditions:: bnf ebnf token INITIAL */ 
/*! Rule::       %% */ 
 this.pushState(ebnf ? 'ebnf' : 'bnf'); return 5; 
break;
case 29 : 
/*! Conditions:: bnf ebnf token INITIAL */ 
/*! Rule::       %ebnf\b */ 
 if (!yy.options) { yy.options = {}; } ebnf = yy.options.ebnf = true; 
break;
case 30 : 
/*! Conditions:: bnf ebnf token INITIAL */ 
/*! Rule::       %debug\b */ 
 if (!yy.options) { yy.options = {}; } yy.options.debug = true; 
break;
case 37 : 
/*! Conditions:: bnf ebnf token INITIAL */ 
/*! Rule::       %token\b */ 
 this.pushState('token'); return 18; 
break;
case 39 : 
/*! Conditions:: bnf ebnf token INITIAL */ 
/*! Rule::       %options\b */ 
 this.pushState('options'); return 24; 
break;
case 41 : 
/*! Conditions:: INITIAL ebnf bnf code */ 
/*! Rule::       %include\b */ 
 this.pushState('path'); return 77; 
break;
case 42 : 
/*! Conditions:: bnf ebnf token INITIAL */ 
/*! Rule::       %{NAME}[^\r\n]* */ 
  
                                            /* ignore unrecognized decl */
                                            console.warn('ignoring unsupported parser option: ', yy_.yytext, ' while lexing in ', this.topState(), ' state');
                                            return 23;
                                         
break;
case 43 : 
/*! Conditions:: bnf ebnf token INITIAL */ 
/*! Rule::       <{ID}> */ 
 yy_.yytext = yy_.yytext.substr(1, yy_.yyleng - 2); return 43; 
break;
case 44 : 
/*! Conditions:: bnf ebnf token INITIAL */ 
/*! Rule::       \{\{[\w\W]*?\}\} */ 
 yy_.yytext = yy_.yytext.substr(2, yy_.yyleng - 4); return 11; 
break;
case 45 : 
/*! Conditions:: bnf ebnf token INITIAL */ 
/*! Rule::       %\{(.|\r|\n)*?%\} */ 
 yy_.yytext = yy_.yytext.substr(2, yy_.yytext.length - 4); return 11; 
break;
case 46 : 
/*! Conditions:: bnf ebnf token INITIAL */ 
/*! Rule::       \{ */ 
 yy.depth = 0; this.pushState('action'); return 70; 
break;
case 47 : 
/*! Conditions:: bnf ebnf token INITIAL */ 
/*! Rule::       ->.* */ 
 yy_.yytext = yy_.yytext.substr(2, yy_.yyleng - 2); return 73; 
break;
case 48 : 
/*! Conditions:: bnf ebnf token INITIAL */ 
/*! Rule::       {HEX_NUMBER} */ 
 yy_.yytext = parseInt(yy_.yytext, 16); return 44; 
break;
case 49 : 
/*! Conditions:: bnf ebnf token INITIAL */ 
/*! Rule::       {DECIMAL_NUMBER}(?![xX0-9a-fA-F]) */ 
 yy_.yytext = parseInt(yy_.yytext, 10); return 44; 
break;
case 50 : 
/*! Conditions:: bnf ebnf token INITIAL */ 
/*! Rule::       . */ 
 
                                            throw new Error("unsupported input character: " + yy_.yytext + " @ " + JSON.stringify(yy_.yylloc)); /* b0rk on bad characters */
                                         
break;
case 54 : 
/*! Conditions:: action */ 
/*! Rule::       \/[^ /]*?['"{}'][^ ]*?\/ */ 
 return 75; // regexp with braces or quotes (and no spaces) 
break;
case 59 : 
/*! Conditions:: action */ 
/*! Rule::       \{ */ 
 yy.depth++; return 70; 
break;
case 60 : 
/*! Conditions:: action */ 
/*! Rule::       \} */ 
 if (yy.depth === 0) { this.popState(); } else { yy.depth--; } return 72; 
break;
case 62 : 
/*! Conditions:: code */ 
/*! Rule::       [^\r\n]+ */ 
 return 80;      // the bit of CODE just before EOF... 
break;
case 63 : 
/*! Conditions:: path */ 
/*! Rule::       [\r\n] */ 
 this.popState(); this.unput(yy_.yytext); 
break;
case 64 : 
/*! Conditions:: path */ 
/*! Rule::       '[^\r\n]+' */ 
 yy_.yytext = yy_.yytext.substr(1, yy_.yyleng - 2); this.popState(); return 78; 
break;
case 65 : 
/*! Conditions:: path */ 
/*! Rule::       "[^\r\n]+" */ 
 yy_.yytext = yy_.yytext.substr(1, yy_.yyleng - 2); this.popState(); return 78; 
break;
case 66 : 
/*! Conditions:: path */ 
/*! Rule::       \s+ */ 
 // skip whitespace in the line 
break;
case 67 : 
/*! Conditions:: path */ 
/*! Rule::       [^\s\r\n]+ */ 
 this.popState(); return 78; 
break;
default:
  return this.simpleCaseActionClusters[$avoiding_name_collisions];
}
},
simpleCaseActionClusters: {

  /*! Conditions:: ebnf */ 
  /*! Rule::       \( */ 
   4 : 64,
  /*! Conditions:: ebnf */ 
  /*! Rule::       \) */ 
   5 : 65,
  /*! Conditions:: ebnf */ 
  /*! Rule::       \* */ 
   6 : 66,
  /*! Conditions:: ebnf */ 
  /*! Rule::       \? */ 
   7 : 67,
  /*! Conditions:: ebnf */ 
  /*! Rule::       \+ */ 
   8 : 68,
  /*! Conditions:: options */ 
  /*! Rule::       {NAME} */ 
   9 : 28,
  /*! Conditions:: options */ 
  /*! Rule::       = */ 
   10 : 29,
  /*! Conditions:: options */ 
  /*! Rule::       [^\s\r\n]+ */ 
   13 : 30,
  /*! Conditions:: bnf ebnf token INITIAL */ 
  /*! Rule::       {ID} */ 
   21 : 63,
  /*! Conditions:: token */ 
  /*! Rule::       [^\s\r\n]+ */ 
   24 : 'TOKEN_WORD',
  /*! Conditions:: bnf ebnf token INITIAL */ 
  /*! Rule::       : */ 
   25 : 50,
  /*! Conditions:: bnf ebnf token INITIAL */ 
  /*! Rule::       ; */ 
   26 : 52,
  /*! Conditions:: bnf ebnf token INITIAL */ 
  /*! Rule::       \| */ 
   27 : 53,
  /*! Conditions:: bnf ebnf token INITIAL */ 
  /*! Rule::       %parser-type\b */ 
   31 : 33,
  /*! Conditions:: bnf ebnf token INITIAL */ 
  /*! Rule::       %prec\b */ 
   32 : 69,
  /*! Conditions:: bnf ebnf token INITIAL */ 
  /*! Rule::       %start\b */ 
   33 : 14,
  /*! Conditions:: bnf ebnf token INITIAL */ 
  /*! Rule::       %left\b */ 
   34 : 36,
  /*! Conditions:: bnf ebnf token INITIAL */ 
  /*! Rule::       %right\b */ 
   35 : 37,
  /*! Conditions:: bnf ebnf token INITIAL */ 
  /*! Rule::       %nonassoc\b */ 
   36 : 38,
  /*! Conditions:: bnf ebnf token INITIAL */ 
  /*! Rule::       %parse-param\b */ 
   38 : 31,
  /*! Conditions:: bnf ebnf token INITIAL */ 
  /*! Rule::       %lex[\w\W]*?{BR}\s*\/lex\b */ 
   40 : 16,
  /*! Conditions:: * */ 
  /*! Rule::       $ */ 
   51 : 8,
  /*! Conditions:: action */ 
  /*! Rule::       \/\*(.|\n|\r)*?\*\/ */ 
   52 : 75,
  /*! Conditions:: action */ 
  /*! Rule::       \/\/.* */ 
   53 : 75,
  /*! Conditions:: action */ 
  /*! Rule::       "(\\\\|\\"|[^"])*" */ 
   55 : 75,
  /*! Conditions:: action */ 
  /*! Rule::       '(\\\\|\\'|[^'])*' */ 
   56 : 75,
  /*! Conditions:: action */ 
  /*! Rule::       [/"'][^{}/"']+ */ 
   57 : 75,
  /*! Conditions:: action */ 
  /*! Rule::       [^{}/"']+ */ 
   58 : 75,
  /*! Conditions:: code */ 
  /*! Rule::       [^\r\n]*(\r|\n)+ */ 
   61 : 80
},
rules: [
/^(?:\r|\n)/,
/^(?:%%)/,
/^(?:;)/,
/^(?:%%)/,
/^(?:\()/,
/^(?:\))/,
/^(?:\*)/,
/^(?:\?)/,
/^(?:\+)/,
/^(?:([a-zA-Z_](?:[a-zA-Z0-9_-]*[a-zA-Z0-9_])?))/,
/^(?:=)/,
/^(?:"(\\\\|\\"|[^"])*")/,
/^(?:'(\\\\|\\'|[^'])*')/,
/^(?:[^\s\r\n]+)/,
/^(?:(\r\n|\n|\r)+)/,
/^(?:\s+(\r\n|\n|\r)+)/,
/^(?:\s+)/,
/^(?:\s+)/,
/^(?:\/\/.*)/,
/^(?:\/\*(.|\n|\r)*?\*\/)/,
/^(?:\[([a-zA-Z_][a-zA-Z0-9_]*)\])/,
/^(?:([a-zA-Z_][a-zA-Z0-9_]*))/,
/^(?:"[^"]+")/,
/^(?:'[^']+')/,
/^(?:[^\s\r\n]+)/,
/^(?::)/,
/^(?:;)/,
/^(?:\|)/,
/^(?:%%)/,
/^(?:%ebnf\b)/,
/^(?:%debug\b)/,
/^(?:%parser-type\b)/,
/^(?:%prec\b)/,
/^(?:%start\b)/,
/^(?:%left\b)/,
/^(?:%right\b)/,
/^(?:%nonassoc\b)/,
/^(?:%token\b)/,
/^(?:%parse-param\b)/,
/^(?:%options\b)/,
/^(?:%lex[\w\W]*?(\r\n|\n|\r)\s*\/lex\b)/,
/^(?:%include\b)/,
/^(?:%([a-zA-Z_](?:[a-zA-Z0-9_-]*[a-zA-Z0-9_])?)[^\r\n]*)/,
/^(?:<([a-zA-Z_][a-zA-Z0-9_]*)>)/,
/^(?:\{\{[\w\W]*?\}\})/,
/^(?:%\{(.|\r|\n)*?%\})/,
/^(?:\{)/,
/^(?:->.*)/,
/^(?:(0[xX][0-9a-fA-F]+))/,
/^(?:([1-9][0-9]*)(?![xX0-9a-fA-F]))/,
/^(?:.)/,
/^(?:$)/,
/^(?:\/\*(.|\n|\r)*?\*\/)/,
/^(?:\/\/.*)/,
/^(?:\/[^ \/]*?['"{}'][^ ]*?\/)/,
/^(?:"(\\\\|\\"|[^"])*")/,
/^(?:'(\\\\|\\'|[^'])*')/,
/^(?:[\/"'][^{}\/"']+)/,
/^(?:[^{}\/"']+)/,
/^(?:\{)/,
/^(?:\})/,
/^(?:[^\r\n]*(\r|\n)+)/,
/^(?:[^\r\n]+)/,
/^(?:[\r\n])/,
/^(?:'[^\r\n]+')/,
/^(?:"[^\r\n]+")/,
/^(?:\s+)/,
/^(?:[^\s\r\n]+)/
],
conditions: {
  "bnf": {
    "rules": [
      3,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44,
      45,
      46,
      47,
      48,
      49,
      50,
      51
    ],
    "inclusive": true
  },
  "ebnf": {
    "rules": [
      3,
      4,
      5,
      6,
      7,
      8,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44,
      45,
      46,
      47,
      48,
      49,
      50,
      51
    ],
    "inclusive": true
  },
  "token": {
    "rules": [
      0,
      1,
      2,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      42,
      43,
      44,
      45,
      46,
      47,
      48,
      49,
      50,
      51
    ],
    "inclusive": true
  },
  "action": {
    "rules": [
      51,
      52,
      53,
      54,
      55,
      56,
      57,
      58,
      59,
      60
    ],
    "inclusive": false
  },
  "code": {
    "rules": [
      41,
      51,
      61,
      62
    ],
    "inclusive": false
  },
  "path": {
    "rules": [
      51,
      63,
      64,
      65,
      66,
      67
    ],
    "inclusive": false
  },
  "options": {
    "rules": [
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      51
    ],
    "inclusive": false
  },
  "INITIAL": {
    "rules": [
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44,
      45,
      46,
      47,
      48,
      49,
      50,
      51
    ],
    "inclusive": true
  }
}
});
// lexer.JisonLexerError = JisonLexerError;
return lexer;
})();
parser.lexer = lexer;

function Parser () {
  this.yy = {};
}
Parser.prototype = parser;
parser.Parser = Parser;
// parser.JisonParserError = JisonParserError;

return new Parser();
})();




if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = parser;
exports.Parser = parser.Parser;
exports.parse = function () {
  return parser.parse.apply(parser, arguments);
};

}
