#
# You can build each example to its own directory in ./output/<example>
# 

JISON=node ../lib/cli.js

all:

.PHONY: 


ansic:
	$(JISON) ./$@.jison -o ./output/$@/

basic:
	$(JISON) ./$@.jison

basic2:
	$(JISON) ./$@.jison

basic2_lex:
	$(JISON) ./$@.jison

basic_lex:
	$(JISON) ./$@.jison

calculator:
	$(JISON) ./$@.jison

calculator_json:
	$(JISON) ./calculator.json

classy:
	$(JISON) ./$@.jison

classy.jisonlex:
	$(JISON) ./classy.jisonlex

classy_ast:
	$(JISON) ./$@.jison

classy_test.src:
	$(JISON) ./classy_test.src

comments:
	$(JISON) ./$@.jison

dism:
	$(JISON) ./$@.jison

dism_lr0:
	$(JISON) ./$@.jison

documentation--custom-lexer-NIL
	$(JISON) ./documentation--custom-lexer-NIL.js

documentation--custom-lexer-ULcase
	$(JISON) ./documentation--custom-lexer-ULcase.js

documentation--mygenerator
	$(JISON) ./documentation--mygenerator.js

formula:
	$(JISON) ./$@.jison

handlebars:
	$(JISON) ./handlebars.jison.l
	$(JISON) ./handlebars.jison.y

inherited.y:
	$(JISON) ./inherited.y

jscore:
	$(JISON) ./$@.jison

json.js:
	$(JISON) ./json.js

json_ast.js:
	$(JISON) ./json_ast.js

lambdacalc:
	$(JISON) ./$@.jison

nv_classy_ast:
	$(JISON) ./$@.jison

phraser:
	$(JISON) ./$@.jison

precedence:
	$(JISON) ./$@.jison

reduce_conflict:
	$(JISON) ./$@.jison

semwhitespace:
	$(JISON) ./$@.jison

semwhitespace_ex.src:
	$(JISON) ./semwhitespace_ex.src

semwhitespace_lex:
	$(JISON) ./$@.jison

tikiwikiparser:
	$(JISON) ./$@.jison

